name: Generate JSON Schema

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 20.x
  TYPESCRIPT_JSON_SCHEMA_VERSION: "^0.62.0"  # 0.62.0 or higher but less than 1
  PYTHON_VERSION: "3.10"
  # Add Globals for Github actions bot
  GITHUB_ACTIONS_USERNAME: "github-actions[bot]"
  GITHUB_ACTIONS_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"

jobs:
  generate_json_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
           node-version: ${{ env.NODE_VERSION }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install TypeScript JSON Schema
        run: npm install -g typescript-json-schema@${{ env.TYPESCRIPT_JSON_SCHEMA_VERSION }}
      - name: Run TypeScript JSON Schema on Workflow object
        run: |
          npx typescript-json-schema tsconfig.json Workflow --required --noExtraProps > cwl_json_schema.raw.json
      - name: Curate JSON Schema
        run: |
          python3 .github/scripts/curate_autogenerated_schema.py cwl_json_schema.raw.json cwl_json_schema.json
      - name: Update Git Configuration
        run: |
          # Add git configuration
          git config user.name "${GITHUB_ACTIONS_USERNAME}"
          git config user.email "${GITHUB_ACTIONS_EMAIL}"
      - name: Commit JSON Schema
        uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: "cwl_json_schema.json"
          message: "Updating CWL JSON Schema"
          push: true

